In [2]:
import torch
import numpy as np

##Initializing a Tensor

In [3]:
# Directly from data
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [ ]:
# From a Numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [5]:
# From another tensor
# retain the shape and dtype of x_data
x_ones = torch.ones_like(x_data)
print(x_ones)

# you can explicitly override
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.1979, 0.7566],
        [0.9774, 0.6605]])


In [7]:
# 특정 shape의 Tensor 생성
shape = (2, 3, )
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.8126, 0.6269, 0.9878],
        [0.2957, 0.6174, 0.2115]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


##Attributes of a Tensor
- shape
- dtype
- the device on which they are stored

In [8]:
tensor = torch.rand(3, 4)

print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.float32
cpu


##Operation on Tensros
- By default, tensors are created on the GPU.
- We need to explicitly move tensors to the GPU using `.to` method.

In [11]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [19]:
# Standard numpy-like indexing and slicing
tensor = torch.rand(4, 4)
print(tensor)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:, 1] = 0
print(tensor)

tensor([[0.0886, 0.7662, 0.6704, 0.6244],
        [0.5379, 0.2503, 0.9020, 0.6673],
        [0.8354, 0.0026, 0.0953, 0.9164],
        [0.3636, 0.0740, 0.9465, 0.0758]])
First row: tensor([0.0886, 0.7662, 0.6704, 0.6244])
First column: tensor([0.0886, 0.5379, 0.8354, 0.3636])
Last column: tensor([0.6244, 0.6673, 0.9164, 0.0758])
tensor([[0.0886, 0.0000, 0.6704, 0.6244],
        [0.5379, 0.0000, 0.9020, 0.6673],
        [0.8354, 0.0000, 0.0953, 0.9164],
        [0.3636, 0.0000, 0.9465, 0.0758]])


In [23]:
# Joining tensors using torch.cat
tensor = torch.ones(4, 4)
tensor[:, 1] = 0
t1 = torch.cat([tensor, tensor, tensor], dim=0)
print(t1)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [25]:
# Arithmetic operations

# This computes the matrix multiplicaiton between two tensors. y1 == y2 == y3
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

# This computes the element-wise product. z1 == z2 == z3
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor.T, out=z3)

tensor([[1., 0., 1., 1.],
        [0., 0., 0., 0.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [27]:
# Signle-element tensors

# Convert it to Python numerical value using item()
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [29]:
# In-place operations: operations that store the result into the operand

print(tensor)
tensor.add_(5)
print(tensor)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])
tensor([[11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.],
        [11., 10., 11., 11.]])


##Bridge with Numpy
- Tensors on the CPU and Numpy arrays can share their underlying memory locations
- and changing one will change the other.

In [30]:
t = torch.ones(5)
print(t)
n = t.numpy()
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [31]:
t.add_(1)
print(t)
print(n)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


##Numpy array to Tensor

In [32]:
n = np.ones(5)
t = torch.from_numpy(n)

In [33]:
np.add(n, 1, out=n)
print(t)
print(n)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
